server:
  port: 18010
spring:
  application:
    name: isc-config-service
  redis:
    host: localhost
    port: 16379
    lettuce:
      pool:
        max-active: 40
        max-idle: 10
        max-wait: 2000ms
        min-idle: 5
      shutdown-timeout: 200ms
      timeout: 2000ms

biz:
  url:
    d: http://localhost:18003
